#!/usr/bin/env node
// Regenerates tension-map.html from beats.csv + cards.csv, then lints the
// spine against the pacing design rules. Run from anywhere:
//   node pacing/sync.mjs
// The CSVs are the source of truth; the marked blocks in tension-map.html
// are overwritten on every run.

import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const DIR = dirname(fileURLToPath(import.meta.url));

// Act display names — extend when the act structure changes.
const ACT_NAMES = {
  1: 'Act 1 · The Garage',
  2: 'Act 2 · The Stand',
  3: 'Act 3 · The Boom',
  4: 'Act 4 · The Bust',
  5: 'Act 5 · The Table',
};

// ---------- CSV ----------
function parseCSV(text) {
  const rows = [];
  let row = [], field = '', quoted = false;
  text = text.replace(/\r\n?/g, '\n');
  for (let i = 0; i < text.length; i++) {
    const ch = text[i];
    if (quoted) {
      if (ch === '"') {
        if (text[i + 1] === '"') { field += '"'; i++; } else quoted = false;
      } else field += ch;
    } else if (ch === '"') quoted = true;
    else if (ch === ',') { row.push(field); field = ''; }
    else if (ch === '\n') { row.push(field); rows.push(row); row = []; field = ''; }
    else field += ch;
  }
  if (field !== '' || row.length) { row.push(field); rows.push(row); }
  const head = rows.shift();
  return rows
    .filter(r => r.some(v => v.trim() !== ''))
    .map(r => Object.fromEntries(head.map((h, k) => [h.trim(), (r[k] ?? '').trim()])));
}

const beats = parseCSV(readFileSync(join(DIR, 'beats.csv'), 'utf8'));
const cards = parseCSV(readFileSync(join(DIR, 'cards.csv'), 'utf8'));

// ---------- validation (hard errors) ----------
const errors = [];
beats.forEach((b, k) => {
  if (+b.beat !== k + 1) errors.push(`beats.csv row ${k + 2}: beat "${b.beat}" — numbering must be contiguous from 1 (expected ${k + 1})`);
  for (const col of ['intensity', 'suspense']) {
    const v = Number(b[col]);
    if (!Number.isFinite(v) || v < 0 || v > 10) errors.push(`beat ${b.beat}: ${col} "${b[col]}" is not a number in 0–10`);
  }
  if (!ACT_NAMES[+b.act]) errors.push(`beat ${b.beat}: act "${b.act}" has no name — add it to ACT_NAMES in sync.mjs`);
  if (k > 0 && +b.act < +beats[k - 1].act) errors.push(`beat ${b.beat}: act number decreases`);
});
cards.forEach(c => {
  if (!c.card) errors.push('cards.csv: a row has an empty card name');
  if (!c.dealt_beat) errors.push(`card "${c.card}": missing dealt_beat`);
});
if (errors.length) {
  console.error('✗ data errors — nothing regenerated:\n  ' + errors.join('\n  '));
  process.exit(1);
}

// ---------- build the data block ----------
const B = beats.map(b => {
  const o = { t: b.title, a: +b.act, i: +b.intensity, s: +b.suspense };
  if (b.hard_out) o.out = 1;
  if (b.essie) o.e = b.essie;
  if (b.denise) o.d = b.denise;
  if (b.near_miss) o.n = b.near_miss;
  if (b.card_dealt) o.c = b.card_dealt;
  if (b.cards_cashed) o.x = 1;
  return o;
});
const ACTS = Object.keys(ACT_NAMES).map(Number)
  .filter(a => B.some(b => b.a === a))
  .map(a => ({
    n: ACT_NAMES[a],
    from: B.findIndex(b => b.a === a),
    to: B.length - 1 - [...B].reverse().findIndex(b => b.a === a),
  }));

const dataBlock =
`// DATA:BEGIN (generated by sync.mjs from beats.csv + cards.csv — edit the CSVs, not this block)
  // beat fields: t title, a act, i intensity, s suspense, out hard-out,
  // e Essie year, d Denise page, n near-miss, c card dealt, x cards cashed
  const B = [
${B.map(o => '    ' + JSON.stringify(o)).join(',\n')}
  ];
  const ACTS = [
${ACTS.map(o => '    ' + JSON.stringify(o)).join(',\n')}
  ];
  // DATA:END`;

const esc = s => s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
const cardRows = cards.map(c => {
  const dealt = `${c.dealt_beat} · ${esc(c.dealt_label)}`;
  const cashed = c.cashed_beat ? `${c.cashed_beat} · ${esc(c.cashed_label)}` : esc(c.cashed_label);
  const held = c.cashed_beat ? String(+c.cashed_beat - +c.dealt_beat) : '—';
  const detail = c.detail ? ` — ${esc(c.detail)}` : '';
  return `        <tr><td><span class="b">${esc(c.card)}</span>${detail}</td><td>${dealt}</td><td>${cashed}</td><td class="num">${held}</td></tr>`;
}).join('\n');
const cardsBlock =
`<!-- CARDS:BEGIN (generated by sync.mjs from cards.csv) -->
${cardRows}
        <!-- CARDS:END -->`;

// ---------- rewrite the HTML ----------
const htmlPath = join(DIR, 'tension-map.html');
const before = readFileSync(htmlPath, 'utf8');
if (!/\/\/ DATA:BEGIN[\s\S]*?\/\/ DATA:END/.test(before) || !/<!-- CARDS:BEGIN[\s\S]*?<!-- CARDS:END -->/.test(before)) {
  console.error('✗ tension-map.html is missing its DATA/CARDS markers — restore them before running sync');
  process.exit(1);
}
const html = before
  .replace(/\/\/ DATA:BEGIN[\s\S]*?\/\/ DATA:END/, () => dataBlock)
  .replace(/<!-- CARDS:BEGIN[\s\S]*?<!-- CARDS:END -->/, () => cardsBlock);
if (html !== before) writeFileSync(htmlPath, html);
console.log(`✓ tension-map.html: ${B.length} beats, ${ACTS.length} acts, ${cards.length} cards${html === before ? ' (already up to date)' : ' regenerated'}`);

// ---------- pacing lint (advisory — judgment stays with the author) ----------
const warn = [], info = [], ok = [];
const beatNo = i => i + 1;

// climax = highest-intensity beat (latest wins a tie)
let climax = 0;
B.forEach((b, i) => { if (b.i >= B[climax].i) climax = i; });

// 1. back-to-back sirens ("every bang buys a breath")
const sirens = [];
for (let k = 1; k < B.length; k++) {
  if (k === climax) continue; // the climax may crowd its neighbor
  if (B[k].i >= 8 && B[k - 1].i >= 8) sirens.push(`beats ${beatNo(k - 1)}–${beatNo(k)}: both intensity ≥ 8`);
  if (B[k].out && B[k - 1].out) sirens.push(`beats ${beatNo(k - 1)}–${beatNo(k)}: consecutive hard outs`);
}
if (sirens.length) sirens.forEach(s => warn.push(`back-to-back sirens — ${s}`));
else ok.push('no back-to-back sirens');

// 2. rising floor, measured on felt tension max(i, s) so a quiet-but-suspenseful
//    scene (the supper table) doesn't read as a leak
const felt = b => Math.max(b.i, b.s);
let prevFloor = -1, prevName = '';
let floorClean = true;
for (const a of ACTS) {
  const idx = [];
  for (let i = a.from; i <= Math.min(a.to, climax); i++) idx.push(i);
  if (!idx.length) continue; // act entirely post-climax
  const minIdx = idx.reduce((m, i) => (felt(B[i]) < felt(B[m]) ? i : m), idx[0]);
  const floor = felt(B[minIdx]);
  if (prevFloor >= 0 && floor < prevFloor) {
    warn.push(`falling floor — ${a.n}'s quietest pre-climax beat (${beatNo(minIdx)}: felt tension ${floor}) sits below ${prevName}'s floor (${prevFloor})`);
    floorClean = false;
  }
  prevFloor = floor; prevName = a.n;
}
if (floorClean) ok.push('the felt-tension floor rises act over act');

// 3. gap closure — suspense below intensity between the first card deal and the
//    climax (excluding cash-in beats, where the collapse is the point)
const firstDeal = B.findIndex(b => b.c);
const dips = [];
for (let i = firstDeal + 1; i < climax; i++) {
  if (!B[i].x && B[i].s < B[i].i) dips.push(i);
}
if (dips.length) {
  // group consecutive runs
  const runs = [];
  for (const i of dips) {
    const r = runs[runs.length - 1];
    if (r && i === r.to + 1) r.to = i; else runs.push({ from: i, to: i });
  }
  for (const r of runs) {
    const span = r.from === r.to ? `beat ${beatNo(r.from)}` : `beats ${beatNo(r.from)}–${beatNo(r.to)}`;
    const sev = r.to - r.from >= 1 ? warn : info;
    sev.push(`irony gap dips — ${span}: suspense below intensity (${r.from === r.to ? `${B[r.from].s} < ${B[r.from].i}` : 'sustained'})${r.to - r.from >= 1 ? ' — the reader has run out of cards here' : ' (single beat; normal at a hard out)'}`);
  }
} else ok.push('suspense never falls below intensity between the first deal and the climax');

// 4. card bookkeeping — cross-check cards.csv against beats.csv
const cardErrs = [];
const dealtInBeats = new Map(); // card name -> beat number
beats.forEach(b => { if (b.card_dealt) dealtInBeats.set(b.card_dealt, +b.beat); });
for (const c of cards) {
  const at = dealtInBeats.get(c.card);
  if (at === undefined) cardErrs.push(`"${c.card}" is in cards.csv but no beat deals it (card_dealt must match the card name exactly)`);
  else if (at !== +c.dealt_beat) cardErrs.push(`"${c.card}": cards.csv says dealt at ${c.dealt_beat}, beats.csv deals it at ${at}`);
  if (c.cashed_beat) {
    const bb = beats[+c.cashed_beat - 1];
    if (!bb || !bb.cards_cashed) cardErrs.push(`"${c.card}": cashes at beat ${c.cashed_beat}, but that beat is not flagged cards_cashed in beats.csv`);
    const held = +c.cashed_beat - +c.dealt_beat;
    if (held < 5) warn.push(`short-held card — "${c.card}" held only ${held} beats (dealt ${c.dealt_beat}, cashed ${c.cashed_beat}); a card needs time to generate pressure`);
  } else {
    info.push(`open card — "${c.card}" (dealt ${c.dealt_beat}) has no cash-in beat yet: ${c.cashed_label || 'unresolved'}`);
  }
}
for (const [name, at] of dealtInBeats) {
  if (!cards.some(c => c.card === name)) cardErrs.push(`beat ${at} deals "${name}" but it has no row in cards.csv`);
}
if (cardErrs.length) cardErrs.forEach(e => warn.push(`card mismatch — ${e}`));
else ok.push('cards.csv and beats.csv agree on every deal and cash-in');

// 5. strand starvation — longest stretch with no strand event, card, or near-miss
const hasEvent = b => b.e || b.d || b.n || b.c || b.x;
let runStart = -1, longest = { len: 0, from: 0, to: 0 };
B.forEach((b, i) => {
  if (hasEvent(b)) { runStart = -1; return; }
  if (runStart < 0) runStart = i;
  const len = i - runStart + 1;
  if (len > longest.len) longest = { len, from: runStart, to: i };
});
if (longest.len >= 6) warn.push(`strand starvation — beats ${beatNo(longest.from)}–${beatNo(longest.to)} (${longest.len} beats) pass with no strand event, card, or near-miss`);
else info.push(`longest quiet stretch (no strand event, card, or near-miss): beats ${beatNo(longest.from)}–${beatNo(longest.to)} (${longest.len} beats)`);

// ---------- report ----------
console.log(`\nPacing lint — climax at beat ${beatNo(climax)} ("${B[climax].t}")`);
for (const s of warn) console.log('  ⚠ ' + s);
for (const s of info) console.log('  · ' + s);
for (const s of ok) console.log('  ✓ ' + s);
if (!warn.length) console.log('  ✓ no rule violations');
